### ISSUE TITLE
Release a new version that fixes the SQL_C_WCHAR issue

### ISSUE THREAD

**Issue by yuga** [hdbc/hdbc-odbc#19]
The latest version 2.4.0.0 of HDBC-odbc on hackage has an issue related to SQL_C_WCHAR.
That issue had been fixed at ab03a6b944f0e5d4901de3b646f321b54211225d.
Would you release a new version?

**Comment by hesselink** [comment]
@anton-dessiatov Are you still maintaining this package? If not, I can make a release.

**Comment by anton-dessiatov** [comment]
Whooops, sorry for that. Somehow I never remembered to make a release.

Version 2.4.0.1 is now on Hackage.

**Comment by yuga** [comment]
@anton-dessiatov thanks!
