### ISSUE TITLE
Memory Leak on Windows

### ISSUE THREAD

**Issue by bhillis** [hdbc/hdbc-odbc#20]
When using the Haskell HDBC-ODBC library to connect to a Microsoft SQL Server I am experiencing a bad memory leak.

    import           Database.HDBC        
    import qualified Database.HDBC.ODBC   as ODBC
    import           Control.Monad
    
    -- | Main application.
    main :: IO ()
    main = dbTest
    
    dbTest :: IO ()
    dbTest = do
        let connStr = "DSN=TESTDB;Uid=sa;Pwd=password"
        conn <- ODBC.connectODBC connStr
        replicateM_ 20000 (loop conn)
        disconnect conn
      where
        loop c = do
            result <- getTables c
            commit c
            putStrLn $ show result

Running the heap profiler gives me constant memory usage but Window reports memory increasing to almost 100MB of usage.

http://i.stack.imgur.com/YkUTW.png

To me this seems like the memory leak is in the Foreign Function interface of the ODBC driver, but this is my first time profiling code so I can't be certain.

**Comment by anton-dessiatov** [comment]
I'm on vacation now, will be back in two weeks and will look on this closely.

Please know that there is v2.5 branch in this github repository. It has memory management reworked significantly and also has no known threading issues. The downside is that it requires patched version of HDBC with this pull request applied: https://github.com/hdbc/hdbc/pull/32

You could give v2.5 branch a try.

**Comment by bhillis** [comment]
Just confirming that the v2.5 branch with the recommended pull request fixed the issue. Thanks for your help.

**Comment by TravisCardwell** [comment]
We ran into this issue at my company in a server application (on Debian).
The application would continually leak memory over time and eventually
raise alarms in our monitoring system.  After debugging the issue with
Valgrind, we implemented a quick fix: manually calling `finish` in order
to free statement resources.

I have confirmed that the v2.5 branch resolves the issue in my test cases
as well.

**Comment by TravisCardwell** [comment]
Checking out the commits to the v2.5 branch, I realized that the breaking
change to HDBC is not necessary in order to resolve the memory leak issue.
Perhaps it would be worthwhile to comment out [the finalize assignment](https://github.com/hdbc/hdbc-odbc/blob/194fc80a28e20d46b40fb5fe74d56c5d19a23e0d/Database/HDBC/ODBC/Statement.hsc#L110) in
order to move forward with the other changes, and then considering the
addition of `finalize` to `Statement` separately.

**Comment by anton-dessiatov** [comment]
Good idea!

I have done it and updated 'master' branch. Could you please test that it builds and works with currently released HDBC (which is 2.4.0.1). If it does, I will upload it to Hackage.

**Comment by TravisCardwell** [comment]
No problem!  I can easily test for the heap leak, but please note that my
test does not cover other possible changes.

* Using HDBC 2.4.0.1 (from Hackage), the HDBC-odbc `master` branch builds 
  fine, and my test passes.
  
* Using the HDBC `master` branch, the HDBC-odbc `master` branch builds 
  fine, and my test passes.

**Comment by anton-dessiatov** [comment]
Uploaded HDBC-odbc-2.5.0.0 to Hackage. Closing this issue now.
